### PR TITLE
Implementation of GetAncestors

### PR DESCRIPTION
**Pull request by bornemix**

### CODE REVIEW

**Comment by frederikvig** [comment]
Hi Björn! Your code will include the root page, which in most cases is not something you'd want. Take a look at this code: https://www.coderesort.com/p/epicode/browser/EPiCode.Extensions/trunk/EPiCode.Extensions/PageData/TraversingExtensions.cs, what do you think?

**Comment by bornemix** [comment]
How about including a parameter (includeRootPage = false) ?

måndag 23 februari 2015 skrev Frederik Vig <notifications@github.com>:

**Comment by frederikvig** [comment]
Agree, includeRootPage sounds good. Can you update your code and I'll merge your pull request? Thanks!

**Comment by bornemix** [comment]
Just following up: (bump)

**Comment by frederikvig** [comment]
You had a missing parameter, fixed now and package created (1.2.0.2). Should be up on nuget.episerver.com in a day or two.

Frederik

**Pull request merged**
